export const GET_ALL_TIMESLOTS_START = "TIMESLOTS@GET_ALL_TIMESLOTS_START";
export const GET_ALL_TIMESLOTS_SUCCESS = "TIMESLOTS@GET_ALL_TIMESLOTS_SUCCESS";
export const GET_ALL_TIMESLOTS_FAILURE = "TIMESLOTS@GET_ALL_TIMESLOTS_FAILURE";
